{{/*apiVersion: v1*/}}
{{/*kind: Service*/}}
{{/*metadata:*/}}
{{/*  name: {{ include "helm.fullname" . }}*/}}
{{/*  labels:*/}}
{{/*    {{- include "helm.labels" . | nindent 4 }}*/}}
{{/*spec:*/}}
{{/*  type: {{ .Values.service.type }}*/}}
{{/*  ports:*/}}
{{/*    - port: {{ .Values.service.port }}*/}}
{{/*      targetPort: http*/}}
{{/*      protocol: TCP*/}}
{{/*      name: http*/}}
{{/*  selector:*/}}
{{/*    {{- include "helm.selectorLabels" . | nindent 4 }}*/}}

{{/*---*/}}
apiVersion: v1
kind: Service
metadata:
  name: sail-map-api-service
  namespace: oscar-dev
spec:
  selector:
    app: sail-map-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000