apiVersion: apps/v1
kind: Deployment
metadata:
  name: sail-map-api
  labels:
    app: sail-map-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sail-map-api
  template:
    metadata:
      labels:
        app: sail-map-api
    spec:
      containers:
        - name: sail-map-api
          image: earlybirdreal/sail-map-api:d1857ba32c7fa4c96e79bc3853cf4eee6fc7fa45
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "0.2"
              memory: "300Mi"
            requests:
              cpu: "0.1"
              memory: "50Mi"
          env:
            - name: COSMOSDB_ENDPOINT
              valueFrom:
                  secretKeyRef:
                    name: cosmosdb-secret
                    key: COSMOSDB-ENDPOINT
            - name: COSMOSDB_KEY
              valueFrom:
                  secretKeyRef:
                      name: cosmosdb-secret
                      key: COSMOSDB-KEY
            - name: DATABASE_ID
              valueFrom:
                  secretKeyRef:
                      name: cosmosdb-secret
                      key: DATABASE-ID
            - name: LOCATION_CONTAINER_ID
              valueFrom:
                  secretKeyRef:
                      name: cosmosdb-secret
                      key: LOCATION-CONTAINER-ID
            - name: UTILITY_CONTAINER_ID
              valueFrom:
                  secretKeyRef:
                      name: cosmosdb-secret
                      key: UTILITY-CONTAINER-ID
      imagePullSecrets:
      - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: sail-map-api-service
spec:
  selector:
    app: sail-map-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sail-map-api-route
spec:
  to:
    kind: Service
    name: sail-map-api-service
  port:
    targetPort: 3000
