apiVersion: apps/v1
kind: Deployment
metadata:
  name: sail-map-api
  namespace: oscar-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sail-map-api
  template:
    metadata:
      labels:
        app: sail-map-api
    spec:
      containers:
        - name: sail-map-api
          image: earlybird/sail-map-api:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: sail-map-api-service
  namespace: oscar-prod
spec:
  selector:
    app: sail-map-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sail-map-api-route
  namespace: oscar-prod
spec:
  to:
    kind: Service
    name: sail-map-api-service
  port:
    targetPort: 80
  tls:
    termination: edge
