apiVersion: v1
kind: Pod
metadata:
  name: sail-map-api
  namespace: oscar-dev
  labels:
    app: sail-map-api
spec:
  containers:
    - name: sail-map-api
      image: earlybirdreal/sail-map-api:latest
      ports:
        - containerPort: 3000
      resources:
        limits:
          cpu: "0.5"
          memory: "500Mi"
        requests:
          cpu: "0.2"
          memory: "50Mi"
  imagePullSecrets:
  - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: sail-map-api-service
  namespace: oscar-dev
spec:
  selector:
    app: sail-map-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sail-map-api-route
  namespace: oscar-dev
spec:
  to:
    kind: Service
    name: sail-map-api-service
  port:
    targetPort: 80
  tls:
    termination: edge
