apiVersion: apps/v1
kind: Deployment
metadata:
  name: sail-map-api
  namespace: oscar-dev
  labels:
    app: sail-map-api
spec:
  replicas: 1  # Single instance
  selector:
    matchLabels:
      app: sail-map-api
  template:
    metadata:
      labels:
        app: sail-map-api
    spec:
      containers:
        - name: sail-map-api
          image: earlybirdreal/sail-map-api:393653e04d57ebb11e35fe8b5663cb77592a7d10
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "0.49"
              memory: "499Mi"
            requests:
              cpu: "0.2"
              memory: "50Mi"
      imagePullSecrets:
      - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: sail-map-api-service
  namespace: oscar-dev
spec:
  selector:
    app: sail-map-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sail-map-api-route
  namespace: oscar-dev
spec:
  to:
    kind: Service
    name: sail-map-api-service
  port:
    targetPort: 3000
