name: Development CI

on:
  push:
    branches:
      - "features/**"
    paths:
      - '**.ts'
      - 'deployment.yml'
  pull_request:
    branches:
      - 'features/**'
    types:
      - opened
      - reopened
      - synchronize

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm
      - run: npm install
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm
      - run: npm install
      - run: npm run test

  deploy:
    runs-on: ubuntu-latest

    needs: [ linting, test ]
    if: |
      (needs.linting.result == 'success') && (needs.test.result == 'success')

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 5: Build and Push Docker Image
      - name: Build and push Docker image
        run: |
          docker build -t earlybirdreal/sail-map-api:${{ github.sha }} .
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username ${{ secrets.DOCKER_ID }} --password-stdin
          docker push earlybirdreal/sail-map-api:${{ github.sha }}

      # Step 6: Deploy to OpenShift
      - name: Update deployment.yml
        run: |
          cd openshift
          sed -i "s|image: earlybirdreal/sail-map-api:.*|image: earlybirdreal/sail-map-api:${{ github.sha }}|" deployment.yml
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add deployment.yml
          git commit -m "Update deployment.yml"
          git push