name: Development CI

on:
  push:
    branches:
      - "features/**"
    paths:
      - '**.ts'
      - 'deployment.yml'
  pull_request:
    branches:
      - 'features/**'
    types:
      - opened
      - reopened
      - synchronize

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm
      - run: npm install
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm
      - run: npm install
      - name: create env file
        run: |
          touch .env
          echo COSMOSDB_ENDPOINT=${{ secrets.COSMOSDB_ENDPOINT }} >> .env
          echo COSMOSDB_KEY=${{ secrets.COSMOSDB_KEY }} >> .env
          echo DATABASE_ID=${{ secrets.DATABASE_ID }} >> .env
          echo LOCATION_CONTAINER_ID=${{ secrets.LOCATION_CONTAINER_ID }} >> .env
          echo UTILITY_CONTAINER_ID=${{ secrets.UTILITY_CONTAINER_ID }} >> .env
      - run: npm run test