name: Deploy to OpenShift

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up OpenShift CLI
      - name: Install OpenShift CLI
        run: |
          curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz | tar -xz -C /usr/local/bin
          oc version

      # Step 3: Log in to OpenShift
      - name: Log in to OpenShift
        run: |
          oc login --token=${{ secrets.OPENSHIFT_TOKEN }} --server=${{ secrets.OPENSHIFT_SERVER }}

      # Step 4: Switch to the target namespace/project
      - name: Switch namespace
        run: |
          oc project oscar-prod

      # Step 5: Build and Push Docker Image
      - name: Build and push Docker image
        run: |
          docker build -t earlybirdreal/sail-map-api:latest .
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username ${{ secrets.DOCKER_ID }} --password-stdin
          docker push earlybirdreal/sail-map-api:latest

      # Step 6: Deploy to OpenShift
      - name: Apply deployment configuration
        run: |
          oc apply -f openshift/deployment.yml
